name: build

on:
  pull_request:
  push:
    paths-ignore:
      - "README.md"
    branches:
      - main
      - releases/*

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        lazarus-versions: [stable, 2.0.12, 2.0.10]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v3.0.16
      with:
        lazarus-version: ${{ matrix.lazarus-versions }}

    - name: Build the Main App (Windows)
      if: ${{ matrix.operating-system == 'windows-latest' }}
      run: lazbuild -B --bm=Release "src/application_config_demo.lpi"

    - name: Build the Main App (Ubuntu)
      if: ${{ matrix.operating-system == 'ubuntu-latest' }}
      run: lazbuild -B --bm=Release "src/application_config_demo.lpi"

    - name: Build the Main App (macOS)
      if: ${{ matrix.operating-system == 'macos-latest' }}
      run: lazbuild -B --bm=Release --ws=cocoa "src/application_config_demo.lpi"
